name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check JSON files are valid JSON
        run: |
          nix-shell --run '
            for file in $(find . -type f -name '*.json'); do
              jq < $file || exit 1
            done
          '
